### ISSUE TITLE
Does not support accessibility 

### ISSUE THREAD

**Issue by bpaul7101** [xPutnikx/flutter-passcode#13]
If we increase the font size via accessibility - the plugin will display spanned text :

**Comment by bpaul7101** [comment]
![image](https://user-images.githubusercontent.com/56043190/72733307-81aa3880-3b8f-11ea-85b4-10428896812c.png)

**Comment by xPutnikx** [comment]
Hi, @bpaul7101 
Do you have any suggestions about how to better solve it?, I guess the same problem might occur with digits as well.
