### ISSUE TITLE
Feature request: just providing widgets for customizations (The Flutter way)

### ISSUE THREAD

**Issue by pixnbit** [xPutnikx/flutter-passcode#16]
First off thanks for this awesome library! 

I feel the API is not flexible enough for me to customize. I would suggest just provide a widget for the header, it's up to the implementer to provide either a "Text('Enter your point') with different styles" or something more creative. 

The same goes to the face of the buttons. You can open up to 9 digits and 1 for the cancel button to either provide just Text or something else. For example, I would like to have an Icon instead of "Cancel" text. Also, the face text can be customized say for non-arabic numerals.

**Comment by xPutnikx** [comment]
@pixnbit thx for your feature request. 
Some stuff you did yourself, which is very appreciated. The other feature of using custom digits will be available in the new version. (Already in master)
