### ISSUE TITLE
Delete button alignment off

### ISSUE THREAD

**Issue by pixnbit** [xPutnikx/flutter-passcode#17]
This is an extreme example, but I noticed it even for smaller screens too.
![Simulator Screen Shot - iPad Air (3rd generation) - 2020-02-25 at 11 45 52](https://user-images.githubusercontent.com/729730/75281654-81234400-57c4-11ea-9cfc-b8f7f8ed3e22.png)

**Comment by xPutnikx** [comment]
Fixed in #18
