### ISSUE TITLE
Example failed to build android, works on IOS

### ISSUE THREAD

**Issue by marcmathys** [xPutnikx/flutter-passcode#21]
Launching lib/main.dart on Android SDK built for x86 in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  /Users/marcmathys/AndroidStudioProjects/example/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:186: error: resource android:attr/fontVariationSettings not found.
  /Users/marcmathys/AndroidStudioProjects/example/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:187: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: /Users/marcmathys/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/18bf3ef7ae11aba806cb141a66e9d4af/aapt2-3.2.1-4818971-osx/aapt2 link -I\
          /Users/marcmathys/Library/Android/sdk/platforms/android-27/android.jar\
          --manifest\
          /Users/marcmathys/AndroidStudioProjects/example/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\
          /Users/marcmathys/AndroidStudioProjects/example/build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\
          @/Users/marcmathys/AndroidStudioProjects/example/build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          /Users/marcmathys/AndroidStudioProjects/example/build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --custom-package\
          com.redeyes.passcodescreen.example\
          -0\
          apk\
          --output-text-symbols\
          /Users/marcmathys/AndroidStudioProjects/example/build/app/intermediates/symbols/debug/R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0
  Output:  /Users/marcmathys/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/9c79557a07b349133747795d92e9553b/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  /Users/marcmathys/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/9c79557a07b349133747795d92e9553b/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: /Users/marcmathys/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/18bf3ef7ae11aba806cb141a66e9d4af/aapt2-3.2.1-4818971-osx/aapt2 link -I\
          /Users/marcmathys/Library/Android/sdk/platforms/android-27/android.jar\
          --manifest\
          /Users/marcmathys/AndroidStudioProjects/example/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\
          /Users/marcmathys/AndroidStudioProjects/example/build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\
          @/Users/marcmathys/AndroidStudioProjects/example/build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          /Users/marcmathys/AndroidStudioProjects/example/build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --custom-package\
          com.redeyes.passcodescreen.example\
          -0\
          apk\
          --output-text-symbols\
          /Users/marcmathys/AndroidStudioProjects/example/build/app/intermediates/symbols/debug/R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by xPutnikx** [comment]
It seems like an issue with android sdk 27. The solution was to update android compile sdk to the latest 27.
Fixed in 11b6ec5c3b54a7e60c36a99efa9785658723b381
