### ISSUE TITLE
Equal replacement for digitSize property

### ISSUE THREAD

**Issue by contactjavas** [xPutnikx/flutter-passcode#24]
I think there was `digitSize` property in the `KeyboardUIConfig`. It seems not available anymore. Now the `KeyboardUIConfig` constructors are:

```dart
const KeyboardUIConfig({
  this.digitBorderWidth = 1,
  this.keyboardRowMargin = const EdgeInsets.only(top: 15, left: 4, right: 4),
  this.digitInnerMargin = const EdgeInsets.all(24),
  this.primaryColor = Colors.white,
  this.digitFillColor = Colors.transparent,
  this.digitTextStyle = const TextStyle(fontSize: 30, color: Colors.white),
  this.deleteButtonTextStyle = const TextStyle(fontSize: 16, color: Colors.white),
  this.keyboardSize,
});
```

What's the equal replacement for `digitSize`? Is it `keyboardSize` or `digitTextStyle`?

**Comment by xPutnikx** [comment]
Hi @contactjavas 
Please use `digitTextStyle` to configure how the items will look like. With that, you get much more flexibility being able to configure not only size but colors, font boldness, etc.

The `keyboardSize` is define as the all size for the keyboard. If it will not be provided the size will be adjusted to screen size.
