### ISSUE TITLE
add reset function

### ISSUE THREAD

**Issue by chitgoks** [xPutnikx/flutter-passcode#25]
to clear programmatically. i am doing a change pin feature using this. currently, i dont see any function in passcode_screen.dart

so a property like
changePin: true

would be nice. so if the user incorrectly enters both pin, a restart button will appear . just a suggestion.

**Comment by xPutnikx** [comment]
I believe features like that should be added by the person who implements the screen. 
Each app has a different logic and many people would like to define their own behaviour. I'm trying to make this widget as simple and as flexible as possible, but don't implement any internal storage, passcode reset etc.

**Comment by chitgoks** [comment]
hi. in that case, then at least having a reset function to be able to call programmatically then?

**Comment by chitgoks** [comment]
a clear function can help greatly. so i can call it programmatically.

there is no way to create a reset workflow if there is no reset function.

thoughts?

**Comment by xPutnikx** [comment]
@chitgoks I can make a reset function which you could call.

**Comment by chitgoks** [comment]
thanks that would be great! thank you @xPutnikx

**Comment by xPutnikx** [comment]
Hi @chitgoks 
I made an example of how the reset function can be done. I'm using the same approach in my own app. 
Please check if it fulfills your needs 
https://github.com/xPutnikx/flutter-passcode/pull/31

**Comment by chitgoks** [comment]
hi. thanks will look into this.
