### ISSUE TITLE
Wrong position of filled circles

### ISSUE THREAD

**Issue by ma-ruz** [xPutnikx/flutter-passcode#26]
When I use a visible (not transparent) fill color for the keyboard circles, the filled circles are drawn at wrong positions. The circle borders are not at the edges of the circle fills and some of the filled circles (different digits depending on the keyboard size) are cut off on the tops.

I use the widget as a child in a SimpleDialog and it looks like this:

```
          Container(
            height: 400,
            width: 300,
            child: PasscodeScreen(
              title: Container(),
              backgroundColor: Colors.white,
              circleUIConfig: CircleUIConfig(
                borderColor: Colors.grey[800],
                fillColor: Colors.grey[800],
              ),
              keyboardUIConfig: KeyboardUIConfig(
                digitTextStyle: const TextStyle(
                  color: Colors.black,
                  fontSize: 25,
                ),
                primaryColor: Colors.white,
                digitFillColor: Colors.grey,
                keyboardSize: Size(220, 320),
              ),
              cancelButton: Container(height: 0, width: 0,),
              deleteButton: Icon(Icons.backspace),
              passwordDigits: 4,
              passwordEnteredCallback: _onPinEntered,
              shouldTriggerVerification: _pinVerificationNotifier.stream,
            ),
          ),

```
I suggest using the digitFillColor as the color of the BoxDecoration rather than the color of the Material.

**Comment by xPutnikx** [comment]
Hi @ma-ruz 
can you give a screenshot as an example? 
I've been trying to reproduce the issue you are talking about, used your code snippet for that. In your example, I see all circles correctly positioned.

**Comment by ma-ruz** [comment]
Hello @xPutnikx ,
I'm attaching a screenshot. It's more noticeable on my tablet than on my phone (probably because of lower resolution) and I used red color as it becomes more apparent.
![Screenshot_2020-10-26-09-15-00 1](https://user-images.githubusercontent.com/61226765/97148652-c80a7480-176b-11eb-911f-fe5e69fde278.png)

**Comment by xPutnikx** [comment]
@ma-ruz thank you for the screenshot! I've been thinking about small circles.
I will have a look at that!

**Comment by xPutnikx** [comment]
Giving an intermediate update. 
I tried to use box decoration, the issue still remains. I found the issue reported in the flutter repo.
https://github.com/flutter/flutter/issues/43159
Going to try to find a workaround for that.

**Comment by xPutnikx** [comment]
@ma-ruz please check the latest version [1.2.2+1] it should solve the issue with borders
