### ISSUE TITLE
Give a child option for 'Forgot passcode'

### ISSUE THREAD

**Issue by AmitJoki** [xPutnikx/flutter-passcode#3]
People forget passcodes sometimes and and therefore there should be a child widget that could be positioned at the bottom of the screen for ('Forgot the password?') kind of Widget.

It would make this aesthatically beautiful Widget more pragmatic.

**Comment by ronaldG19** [comment]
Good idea but, sensitive information such as passwords can be stored in the cloud to be retrieve in different ways you can work on that.
Secondly the screen will be so small for the implementation or lost the flavor by pushing another screen for the forgotten password.

**Comment by AmitJoki** [comment]
I've forked it and made a custom version myself. You can have a look at it in https://github.com/AmitJoki/Enigma

**Comment by xPutnikx** [comment]
@AmitJoki if you are copying my plugin, you need to include copyrights.
Thx.

**Comment by AmitJoki** [comment]
@xPutnikx Hey how should I go about this? Can I include a link to this package in acknowledgements? Or copy the license in the file where I have done modifications over yours? Thanks.

**Comment by xPutnikx** [comment]
@AmitJoki I think it will be fine if you will include the link to my package in acknowledgements.

**Comment by AmitJoki** [comment]
> @AmitJoki I think it will be fine if you will include the link to my package in acknowledgements.

I have done that. Cheers!
